### ISSUE TITLE
Create game against computer

### ISSUE THREAD

**Issue by macleanb** [macleanb/chess_public#1]
(Frontend & Backend) Build on existing new game creation functionality to allow a user to create a new game but this time against the computer.

In Form_GameMenu.js, a player should be able to select their player color and whether they want to play against the computer.  If they select computer, the backend should update the Game field player2_color, game_type, created_datetime, started_datetime, game_status. Display game pieces provided from backend.

Sub-tasks (rough):
1.  Send form data from front-end indicating the second player will be a computer and then update backend POST to GamesView (/games/ endpoint) so that the game_type field is set to 'HUMAN V. COMPUTER'
2. On the frontend, in the Game Controls Form, display the second player as 'Computer' if parentState.gameDataFromServer.game_type === 'HUMAN V. COMPUTER'.  Display whose turn it is as appropriate (if parentState.gameDataFromServer.whose_turn === null AND parentState.gameDataFromServer.game_type === 'HUMAN V. COMPUTER', you know it's the computer's turn).
3. Frontend: we need a useEffect for computer moves.  Watch the dependency array [gameDataFromServer?.whose_turn, gameDataFromServer?.game_type].  If gameDataFromServer.whose_turn === null AND gameDataFromServer.game_type === 'HUMAN V. COMPUTER', get make a call to get a suggested move and then call board_MakeMove with that move.
4. Update the backend PUT to GameView (/games/<int:game_id>/) to set whose_turn to None if player1 just made a move and game_type == 'HUMAN V. COMPUTER'.  Set whose_turn to player1 if a PUT was just received with whose_turn == None and game_type == 'HUMAN V. COMPUTER'.
5. Backend: Update PlayableGames view to only include games in filter result where game_type = 'HUMAN V. HUMAN'

**Comment by w034414532** [comment]
Was considering adding a useState and Toggle function within Form_GameMenu.js like this (with possible a checkbox in FormManage.js):

const [isComputerOpponent, setIsComputerOpponent] = useState(false);

const toggleOpponentType = () => {
  setIsComputerOpponent(!isComputerOpponent);
};

**Comment by w034414532** [comment]
However, I also noticed that there was already a handleNewGameClicked in FormManager.js, so didn't know if it was just easier to add the functionality there instead of in Form_GameMenu.js

**Comment by macleanb** [comment]
Hey Will.  I agree...recommend Form_GameMenu.js.  It may be good design to set the state based on whether a checkbox is checked or not.  Sometimes rapid user interaction can get the state setting out of sync.

**Comment by w034414532** [comment]
Hey Brian, I am still having trouble implementing the functionality. After adding code for handleNewGameClicked, adding the checkbox in Form_GameMenu, and making sure formData_NewGame returned the correct data, the functionality still doesn't work.

**Comment by w034414532** [comment]
Can we do some pair programming tomorrow just to see what I missed? Thanks. I pushed my code to the branch, if you wanted to take a look at it.

**Comment by macleanb** [comment]
Sounds good WIll, no problem.  Thanks for your effort on this.  A couple questions...is your branch all caught up with main?  You may need to a git pull on main and then checkout your feature branch and then do git merge main to make sure all your code incorporates all the other changes.

Also, have you updated the backend POST method to the /games/ endpoint to set the game type to HUMAN V. COMPUTER?

Lastly, I'll add a bit more specificity in the issue description for what tasks we'll need to accomplish to make this work.

**Comment by w034414532** [comment]
Yes, I pulled the latest from main branch and merged it with my branch, before pushing the code to GitHub. I'll take a look at the POST method and will let you know what I find there.

**Comment by macleanb** [comment]
Closing this issue because it will be replaced by #57
