### ISSUE TITLE
Join existing games

### ISSUE THREAD

**Issue by macleanb** [macleanb/chess_public#2]
(Frontend / Backend )
Reference issue https://github.com/macleanb/chess_public/issues/20#issue-2254155146 which should be completed first
Reference issue https://github.com/macleanb/chess_public/issues/34#issue-2261362046 Game.js redesign -- should be completed first

FRONTEND/ BACKEND Setup for CONTINUING games:
- Need backend GameView.get(self, request, game_id) method
- - Logic is similar to PUT method
- Need frontend getURL_Game.js file/function in utils (just copy code from getURL_MakeMove.js)
- Need frontend continueGame() function (api_ContinueGame.js) in utils (similar to api_MakeMove but GET instead of PUT)
- useEffect in Game.js will call continueGame() -- code is already there, just needs to be uncommented

FRONTEND/ BACKEND Setup for JOINING open games:
- Need backend GameView.post(self, request, game_id) method 
- - Logic is similar to PUT method except you need to assign request.user.id to game.player2 (which should have been open), set player2_color (opposite of player1_color), game_type ('HUMAN V. HUMAN' or 'HUMAN V. COMPUTER'), started_datetime, game_status- Need frontend getURL_Game.js file/function in utils (should be accomplished above)
- need frontend joinGame() function (api_JoinGame.js file) in utils (similar to api_ContinueGame above, but POST instead of GET)

FRONTEND FINALIZATION WORK:
In Form_GameMenu GAME_NEW_CONTINUE_MODE allow user to join existing games by clicking a 'Join Game' button.  Also need a display existing games that the user can join (see related issue https://github.com/macleanb/chess_public/issues/20#issue-2254155146).

- (Done) In Game.js, create a state variable: const [ gameFetchData, setGameFetchData ] = useState();
- (Done) In constants.js, create some constants: GAME_FETCH_NEW : 'NEW_GAME', GAME_FETCH_JOIN : 'JOIN_GAME', GAME_FETCH_CONTINUE : 'CONTINUE_GAME'

In FormManager.js handleJoinGameClicked(gameData):
```
    let gameFetchDataObj;
    const userIsPlayer1 = gameData.player1.id === auth.user.id;
    const userIsPlayer2 = gameData.player2 === null ? false : gameData.player2.id === auth.user.id;

    /* If the user WAS already a player in an existing game */
    if (userIsPlayer1 || userIsPlayer2) {
      const playerColor = userIsPlayer1 ? gameData.player1_color : gameData.player2_color;

      gameFetchDataObj = parentState.imports.createGameFetchDataObj(
        playerColor,
        gameData.id,
        parentState.imports.constants.GAME_FETCH_CONTINUE,
        false // playComputer
      );
    } else {
      /* If the user was NOT already a player in an existing game */
      const LIGHT = parentState.imports.constants.COLOR_PIECE_LIGHT;
      const DARK = parentState.imports.constants.COLOR_PIECE_DARK;

      const playerColor = gameData.player1_color ===  LIGHT ? DARK : LIGHT;

      gameFetchDataObj = parentState.imports.createGameFetchDataObj(
        playerColor,
        gameData.id,
        parentState.imports.constants.GAME_FETCH_JOIN,
        false // playComputer
      );
    }

    setGameFetchData(gameFetchDataObj);
```

- In Game.js the useEffect that watches [boardInitializationState]:
- - un-comment the cases for constants.GAME_FETCH_CONTINUE and constants.GAME_FETCH_JOIN.
- useEffects in Game.js will setPlayerColor, initializeBoardData (once playerColor is set), and display game pieces from backend automatically now.

**Comment by chsbca** [comment]
will tackle #32 first before accomplishing this issue

**Comment by chsbca** [comment]
I've done some of the work but not all so @macleanb tomorrow I'd like to ask for your help to pair program this if you're not too busy.
