### ISSUE TITLE
Display existing games

### ISSUE THREAD

**Issue by macleanb** [macleanb/chess_public#20]
(Frontend / Backend ) Display existing games in GAME_NEW_CONTINUE_MODE.
Issue https://github.com/macleanb/chess_public/issues/32#issue-2259829799 should be completed first.

Display a list of exiting games:
- where player2 is unassigned ("open")
- OR
- where logged in user is either player1 or player2 (allow them to rejoin the game)

**Comment by chsbca** [comment]
@macleanb what file do you want me to put the code in? I was wondering if you have a component or something similar. I was thinking just inserting it into Game.js but yea please let me know. I'm very particular with stuff and I don't wanna mess too much with the structure of the code yet while im still trying to fully understand it

**Comment by macleanb** [comment]
Hey @chsbca, sorry for taking so long to notice your message.  I'm thinking Form_GameMenu.js would be a good place to start for this UI.  Beneath the Select/Button for creating a new game.

**Comment by chsbca** [comment]
Will change timing on when api call is done. Ideally when the "Show Playable Games" button is clicked
