### ISSUE TITLE
Finish backend makeMove() functionality

### ISSUE THREAD

**Issue by macleanb** [macleanb/chess_public#4]
( Frontend / Backend )
Ensure related issue is completed first: https://github.com/macleanb/chess_public/issues/21#issue-2254614251

- Update backend GameView PUT functionality. Backend should handle capturing pieces.
- - Should update on_board field on backend Piece model for the piece that was captured.  
- - Should ask OpenAI if the board configuration is a checkmate situation and -- if so -- update game_status, ended_datetime, game_winner on backend Game model.
- - - If game is won, frontend should display a congratulatory message to the winner and lock-out click/drag behavior on pieces.

**Comment by JamesH34** [comment]
This issue was completed with issues 56 and 61.
