### ISSUE TITLE
Add cypress test to check a piece being a disabled when moving it would put King piece in danger

### ISSUE THREAD

**Issue by chsbca** [macleanb/chess_public#62]
![image](https://github.com/macleanb/chess_public/assets/155914185/22d49246-ea07-4576-ba68-a09cf33f6b72)

As seen in the image above, moving selected pawn is disabled due to putting white's king in danger to the black's queen

Making a test to ensure chess module's reliability stays put as we update the code is crucial for code stability

**Comment by macleanb** [comment]
Completed and pull request initiated.
